{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1aec4726",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import *\n",
    "from tkinter import filedialog,messagebox\n",
    "import random\n",
    "import time\n",
    "import requests\n",
    "\n",
    "#Functions\n",
    "\n",
    "def reset():\n",
    "    textReceipt.delete(1.0,END)\n",
    "    e_chapathi.set('0')\n",
    "    e_butternaan.set('0')\n",
    "    e_mushroom.set('0')\n",
    "    e_fish.set('0')\n",
    "    e_manchurian.set('0')\n",
    "    e_rice.set('0')\n",
    "    e_mutton.set('0')\n",
    "    e_paneer.set('0')\n",
    "    e_chicken.set('0')\n",
    "\n",
    "    e_lassi.set('0')\n",
    "    e_coffee.set('0')\n",
    "    e_lemonade.set('0')\n",
    "    e_roohafza.set('0')\n",
    "    e_milkshake.set('0')\n",
    "    e_chocolatemilk.set('0')\n",
    "    e_masalatea.set('0')\n",
    "    e_badammilk.set('0')\n",
    "    e_coldrinks.set('0')\n",
    "\n",
    "    e_kitkat.set('0')\n",
    "    e_oreo.set('0')\n",
    "    e_apple.set('0')\n",
    "    e_vanilla.set('0')\n",
    "    e_banana.set('0')\n",
    "    e_brownie.set('0')\n",
    "    e_pineapple.set('0')\n",
    "    e_chocolate.set('0')\n",
    "    e_blackforest.set('0')\n",
    "\n",
    "    textchapathi.config(state=DISABLED)\n",
    "    textbutternaan.config(state=DISABLED)\n",
    "    textmushroom.config(state=DISABLED)\n",
    "    textfish.config(state=DISABLED)\n",
    "    textmanchurian.config(state=DISABLED)\n",
    "    textpaneer.config(state=DISABLED)\n",
    "    textchicken.config(state=DISABLED)\n",
    "    textmutton.config(state=DISABLED)\n",
    "    textrice.config(state=DISABLED)\n",
    "\n",
    "    textlassi.config(state=DISABLED)\n",
    "    textcoffee.config(state=DISABLED)\n",
    "    textchocolatemilk.config(state=DISABLED)\n",
    "    textroohafza.config(state=DISABLED)\n",
    "    textmilkshake.config(state=DISABLED)\n",
    "    textbadammilk.config(state=DISABLED)\n",
    "    textmasalatea.config(state=DISABLED)\n",
    "    textlemonade.config(state=DISABLED)\n",
    "    textcolddrinks.config(state=DISABLED)\n",
    "\n",
    "    textoreo.config(state=DISABLED)\n",
    "    textapple.config(state=DISABLED)\n",
    "    textkitkat.config(state=DISABLED)\n",
    "    textvanilla.config(state=DISABLED)\n",
    "    textbanana.config(state=DISABLED)\n",
    "    textbrownie.config(state=DISABLED)\n",
    "    textpineapple.config(state=DISABLED)\n",
    "    textchocolate.config(state=DISABLED)\n",
    "    textblackforest.config(state=DISABLED)\n",
    "\n",
    "    var1.set(0)\n",
    "    var2.set(0)\n",
    "    var3.set(0)\n",
    "    var4.set(0)\n",
    "    var5.set(0)\n",
    "    var6.set(0)\n",
    "    var7.set(0)\n",
    "    var8.set(0)\n",
    "    var9.set(0)\n",
    "    var10.set(0)\n",
    "    var11.set(0)\n",
    "    var12.set(0)\n",
    "    var13.set(0)\n",
    "    var14.set(0)\n",
    "    var15.set(0)\n",
    "    var16.set(0)\n",
    "    var17.set(0)\n",
    "    var18.set(0)\n",
    "    var19.set(0)\n",
    "    var20.set(0)\n",
    "    var21.set(0)\n",
    "    var22.set(0)\n",
    "    var23.set(0)\n",
    "    var24.set(0)\n",
    "    var25.set(0)\n",
    "    var26.set(0)\n",
    "    var27.set(0)\n",
    "\n",
    "    costofdrinksvar.set('')\n",
    "    costoffoodvar.set('')\n",
    "    costofcakesvar.set('')\n",
    "    subtotalvar.set('')\n",
    "    servicetaxvar.set('')\n",
    "    totalcostvar.set('')\n",
    "\n",
    "def receipt():\n",
    "    global billnumber,date\n",
    "    if costoffoodvar.get() != '' or costofcakesvar.get() != '' or costofdrinksvar.get() != '':\n",
    "        textReceipt.delete(1.0,END)\n",
    "        x=random.randint(100,10000)\n",
    "        billnumber='BILL'+str(x)\n",
    "        date=time.strftime('%d/%m/%Y')\n",
    "        textReceipt.insert(END,'Receipt Ref:\\t\\t'+billnumber+'\\t\\t'+date+'\\n')\n",
    "        textReceipt.insert(END,'***************************************************************\\n')\n",
    "        textReceipt.insert(END,'Items:\\t\\t Cost Of Items(Rs)\\n')\n",
    "        textReceipt.insert(END,'***************************************************************\\n')\n",
    "        if e_chapathi.get()!='0':\n",
    "            textReceipt.insert(END,f'Chapati\\t\\t\\t{int(e_chapathi.get())*10}\\n\\n')\n",
    "\n",
    "        if e_butternaan.get()!='0':\n",
    "            textReceipt.insert(END,f'Butter Naan\\t\\t\\t{int(e_butternaan.get())*15}\\n\\n')\n",
    "\n",
    "        if e_fish.get()!='0':\n",
    "            textReceipt.insert(END,f'Fish\\t\\t\\t{int(e_fish.get())*100}\\n\\n')\n",
    "\n",
    "        if e_rice.get() != '0':\n",
    "            textReceipt.insert(END, f'Rice:\\t\\t\\t{int(e_rice.get()) * 30}\\n\\n')\n",
    "\n",
    "        if e_mushroom.get() != '0':\n",
    "            textReceipt.insert(END, f'Mushroom:\\t\\t\\t{int(e_mushroom.get()) * 120}\\n\\n')\n",
    "\n",
    "        if e_paneer.get() != '0':\n",
    "            textReceipt.insert(END, f'Paneer:\\t\\t\\t{int(e_paneer.get()) * 100}\\n\\n')\n",
    "\n",
    "        if e_manchurian.get() != '0':\n",
    "            textReceipt.insert(END, f'Manchurian:\\t\\t\\t{int(e_manchurian.get()) * 70}\\n\\n')\n",
    "\n",
    "        if e_chicken.get() != '0':\n",
    "            textReceipt.insert(END, f'Chicken:\\t\\t\\t{int(e_chicken.get()) * 120}\\n\\n')\n",
    "\n",
    "        if e_mutton.get() != '0':\n",
    "            textReceipt.insert(END, f'Mutton:\\t\\t\\t{int(e_mutton.get()) * 120}\\n\\n')\n",
    "\n",
    "        if e_lassi.get() != '0':\n",
    "            textReceipt.insert(END, f'Lassi:\\t\\t\\t{int(e_lassi.get()) * 50}\\n\\n')\n",
    "\n",
    "        if e_coffee.get() != '0':\n",
    "            textReceipt.insert(END, f'Coffee:\\t\\t\\t{int(e_coffee.get()) * 40}\\n\\n')\n",
    "\n",
    "        if e_lemonade.get() != '0':\n",
    "            textReceipt.insert(END, f'Lemonade:\\t\\t\\t{int(e_lemonade.get()) * 80}\\n\\n')\n",
    "\n",
    "        if e_milkshake.get() != '0':\n",
    "            textReceipt.insert(END, f'Milkshake:\\t\\t\\t{int(e_milkshake.get()) * 30}\\n\\n')\n",
    "\n",
    "        if e_chocolatemilk.get() != '0':\n",
    "            textReceipt.insert(END, f'Chocolate milk:\\t\\t\\t{int(e_chocolatemilk.get()) * 40}\\n\\n')\n",
    "\n",
    "        if e_roohafza.get() != '0':\n",
    "            textReceipt.insert(END, f'Green tea:\\t\\t\\t{int(e_roohafza.get()) * 35}\\n\\n')\n",
    "\n",
    "        if e_masalatea.get() != '0':\n",
    "            textReceipt.insert(END, f'Masala Chai:\\t\\t\\t{int(e_masalatea.get()) * 20}\\n\\n')\n",
    "\n",
    "        if e_badammilk.get() != '0':\n",
    "            textReceipt.insert(END, f'Badam Milk:\\t\\t\\t{int(e_badammilk.get()) * 50}\\n\\n')\n",
    "\n",
    "        if e_coldrinks.get() != '0':\n",
    "            textReceipt.insert(END, f'Cold Drinks:\\t\\t\\t{int(e_coldrinks.get()) * 80}\\n\\n')\n",
    "\n",
    "        if e_oreo.get() != '0':\n",
    "            textReceipt.insert(END, f'Butterscotch:\\t\\t\\t{int(e_oreo.get()) * 800}\\n\\n')\n",
    "\n",
    "        if e_apple.get() != '0':\n",
    "            textReceipt.insert(END, f'Normal Cake:\\t\\t\\t{int(e_apple.get()) * 300}\\n\\n')\n",
    "\n",
    "        if e_kitkat.get() != '0':\n",
    "            textReceipt.insert(END, f'Kitkat:\\t\\t\\t{int(e_kitkat.get()) * 500}\\n\\n')\n",
    "\n",
    "        if e_banana.get() != '0':\n",
    "            textReceipt.insert(END, f'Banana:\\t\\t\\t{int(e_banana.get()) * 450}\\n\\n')\n",
    "\n",
    "        if e_brownie.get() != '0':\n",
    "            textReceipt.insert(END, f'Brownie:\\t\\t\\t{int(e_brownie.get()) * 800}\\n\\n')\n",
    "\n",
    "        if e_pineapple.get() != '0':\n",
    "            textReceipt.insert(END, f'Pineapple:\\t\\t\\t{int(e_pineapple.get()) * 620}\\n\\n')\n",
    "\n",
    "        if e_chocolate.get() != '0':\n",
    "            textReceipt.insert(END, f'Chocolate:\\t\\t\\t{int(e_chocolate.get()) * 700}\\n\\n')\n",
    "\n",
    "        if e_blackforest.get() != '0':\n",
    "            textReceipt.insert(END, f'Black Forest:\\t\\t\\t{int(e_blackforest.get()) * 1050}\\n\\n')\n",
    "\n",
    "        if e_vanilla.get() != '0':\n",
    "            textReceipt.insert(END, f'Vanilla:\\t\\t\\t{int(e_vanilla.get()) * 550}\\n\\n')\n",
    "\n",
    "        textReceipt.insert(END,'***************************************************************\\n')\n",
    "        if costoffoodvar.get()!='0 Rs':\n",
    "            textReceipt.insert(END,f'Cost Of Food\\t\\t\\t{priceofFood}Rs\\n\\n')\n",
    "        if costofdrinksvar.get() != '0 Rs':\n",
    "            textReceipt.insert(END,f'Cost Of Drinks\\t\\t\\t{priceofDrinks}Rs\\n\\n')\n",
    "        if costofcakesvar.get() != '0 Rs':\n",
    "            textReceipt.insert(END,f'Cost Of Cakes\\t\\t\\t{priceofCakes}Rs\\n\\n')\n",
    "\n",
    "        textReceipt.insert(END, f'Sub Total\\t\\t\\t{subtotalofItems}Rs\\n\\n')\n",
    "        textReceipt.insert(END, f'Service Tax\\t\\t\\t{20}Rs\\n\\n')\n",
    "        textReceipt.insert(END, f'Total Cost\\t\\t\\t{subtotalofItems+20}Rs\\n\\n')\n",
    "        textReceipt.insert(END,'***************************************************************\\n')\n",
    "\n",
    "    else:\n",
    "        messagebox.showerror('Error','No Item Is selected')\n",
    "\n",
    "\n",
    "\n",
    "def totalcost():\n",
    "    global priceofFood,priceofDrinks,priceofCakes,subtotalofItems\n",
    "    if var1.get() != 0 or var2.get() != 0 or var3.get() != 0 or var4.get() != 0 or var5.get() != 0 or \\\n",
    "        var6.get() != 0 or var7.get() != 0 or var8.get() != 0 or var9.get() != 0 or var10.get() != 0 or\\\n",
    "        var11.get() != 0 or var12.get() != 0 or var13.get() != 0 or var14.get() != 0 or var15.get() != 0 or \\\n",
    "        var16.get() != 0 or var17.get() != 0 or var18.get() != 0 or var19.get() != 0 or var20.get() != 0 or \\\n",
    "        var21.get() != 0 or var22.get() != 0 or var23.get() != 0 or var24.get() != 0 or var25.get() != 0 or\\\n",
    "        var26.get() != 0 or var27.get() != 0:\n",
    "\n",
    "        item1=int(e_chapathi.get())\n",
    "        item2=int(e_butternaan.get())\n",
    "        item3=int(e_fish.get())\n",
    "        item4 = int(e_mushroom.get())\n",
    "        item5 = int(e_manchurian.get())\n",
    "        item6 = int(e_rice.get())\n",
    "        item7 = int(e_mutton.get())\n",
    "        item8 = int(e_paneer.get())\n",
    "        item9 = int(e_chicken.get())\n",
    "\n",
    "        item10 = int(e_lassi.get())\n",
    "        item11 = int(e_coffee.get())\n",
    "        item12 = int(e_lemonade.get())\n",
    "        item13 = int(e_milkshake.get())\n",
    "        item14 = int(e_chocolatemilk.get())\n",
    "        item15 = int(e_roohafza.get())\n",
    "        item16 = int(e_masalatea.get())\n",
    "        item17 = int(e_badammilk.get())\n",
    "        item18 = int(e_coldrinks.get())\n",
    "\n",
    "        item19 = int(e_oreo.get())\n",
    "        item20 = int(e_apple.get())\n",
    "        item21 = int(e_kitkat.get())\n",
    "        item22 = int(e_vanilla.get())\n",
    "        item23 = int(e_banana.get())\n",
    "        item24 = int(e_brownie.get())\n",
    "        item25 = int(e_pineapple.get())\n",
    "        item26 = int(e_chocolate.get())\n",
    "        item27 = int(e_blackforest.get())\n",
    "\n",
    "        priceofFood=(item1*10)+(item2*15)+(item3*100)+(item4*120)+ (item5*70) + (item6 * 30) + (item7 * 120) \\\n",
    "                    + (item8 * 100) + (item9 * 120)\n",
    "\n",
    "        priceofDrinks=(item10*50)+(item11*40)+ (item12 * 80) + (item13 * 30) + (item14 * 40) + (item15 * 35) \\\n",
    "                      + (item16 * 20) + (item17 * 50) + (item18 * 80)\n",
    "\n",
    "        priceofCakes=(item19*800)+(item20*300)+ (item21 * 500) + (item22 * 550) + (item23 * 450) + (item24 * 800) \\\n",
    "                     + (item25 * 620) + (item26 * 700) + (item27 * 1050)\n",
    "\n",
    "        costoffoodvar.set(str(priceofFood)+ ' Rs')\n",
    "        costofdrinksvar.set(str(priceofDrinks)+ ' Rs')\n",
    "        costofcakesvar.set(str(priceofCakes)+ ' Rs')\n",
    "\n",
    "        subtotalofItems=priceofFood+priceofDrinks+priceofCakes\n",
    "        subtotalvar.set(str(subtotalofItems)+' Rs')\n",
    "\n",
    "        servicetaxvar.set('20 Rs')\n",
    "\n",
    "        tottalcost=subtotalofItems+20\n",
    "        totalcostvar.set(str(tottalcost)+' Rs')\n",
    "\n",
    "    else:\n",
    "        messagebox.showerror('Error','No Item Is selected')\n",
    "\n",
    "\n",
    "\n",
    "def chapathi():\n",
    "    if var1.get()==1:\n",
    "        textchapathi.config(state=NORMAL)\n",
    "        textchapathi.delete(0,END)\n",
    "        textchapathi.focus()\n",
    "    else:\n",
    "        textchapathi.config(state=DISABLED)\n",
    "        e_chapathi.set('0')\n",
    "\n",
    "def butternaan():\n",
    "    if var2.get()==1:\n",
    "        textbutternaan.config(state=NORMAL)\n",
    "        textbutternaan.delete(0,END)\n",
    "        textbutternaan.focus()\n",
    "\n",
    "    else:\n",
    "        textbutternaan.config(state=DISABLED)\n",
    "        e_butternaan.set('0')\n",
    "\n",
    "def fish():\n",
    "    if var3.get()==1:\n",
    "        textfish.config(state=NORMAL)\n",
    "        textfish.delete(0,END)\n",
    "        textfish.focus()\n",
    "\n",
    "    else:\n",
    "        textfish.config(state=DISABLED)\n",
    "        e_fish.set('0')\n",
    "\n",
    "def mushroom():\n",
    "    if var4.get() == 1:\n",
    "        textmushroom.config(state=NORMAL)\n",
    "        textmushroom.focus()\n",
    "        textmushroom.delete(0, END)\n",
    "    elif var4.get() == 0:\n",
    "        textmushroom.config(state=DISABLED)\n",
    "        e_mushroom.set('0')\n",
    "\n",
    "\n",
    "def manchurian():\n",
    "    if var5.get() == 1:\n",
    "        textmanchurian.config(state=NORMAL)\n",
    "        textmanchurian.focus()\n",
    "        textmanchurian.delete(0, END)\n",
    "    elif var5.get() == 0:\n",
    "        textmanchurian.config(state=DISABLED)\n",
    "        e_manchurian.set('0')\n",
    "\n",
    "\n",
    "def rice():\n",
    "    if var6.get() == 1:\n",
    "        textrice.config(state=NORMAL)\n",
    "        textrice.focus()\n",
    "        textrice.delete(0, END)\n",
    "    elif var6.get() == 0:\n",
    "        textrice.config(state=DISABLED)\n",
    "        e_rice.set('0')\n",
    "\n",
    "\n",
    "def mutton():\n",
    "    if var7.get() == 1:\n",
    "        textmutton.config(state=NORMAL)\n",
    "        textmutton.focus()\n",
    "        textmutton.delete(0, END)\n",
    "    elif var7.get() == 0:\n",
    "        textmutton.config(state=DISABLED)\n",
    "        e_mutton.set('0')\n",
    "\n",
    "\n",
    "def paneer():\n",
    "    if var8.get() == 1:\n",
    "        textpaneer.config(state=NORMAL)\n",
    "        textpaneer.focus()\n",
    "        textpaneer.delete(0, END)\n",
    "    elif var8.get() == 0:\n",
    "        textpaneer.config(state=DISABLED)\n",
    "        e_paneer.set('0')\n",
    "\n",
    "\n",
    "def chicken():\n",
    "    if var9.get() == 1:\n",
    "        textchicken.config(state=NORMAL)\n",
    "        textchicken.focus()\n",
    "        textchicken.delete(0, END)\n",
    "    elif var9.get() == 0:\n",
    "        textchicken.config(state=DISABLED)\n",
    "        e_chicken.set('0')\n",
    "\n",
    "\n",
    "def lassi():\n",
    "    if var10.get() == 1:\n",
    "        textlassi.config(state=NORMAL)\n",
    "        textlassi.focus()\n",
    "        textlassi.delete(0, END)\n",
    "    elif var10.get() == 0:\n",
    "        textlassi.config(state=DISABLED)\n",
    "        e_lassi.set('0')\n",
    "\n",
    "\n",
    "def coffee():\n",
    "    if var11.get() == 1:\n",
    "        textcoffee.config(state=NORMAL)\n",
    "        textcoffee.focus()\n",
    "        textcoffee.delete(0, END)\n",
    "    elif var11.get() == 0:\n",
    "        textcoffee.config(state=DISABLED)\n",
    "        e_coffee.set('0')\n",
    "\n",
    "\n",
    "def lemonade():\n",
    "    if var12.get() == 1:\n",
    "        textlemonade.config(state=NORMAL)\n",
    "        textlemonade.focus()\n",
    "        textlemonade.delete(0, END)\n",
    "    elif var12.get() == 0:\n",
    "        textlemonade.config(state=DISABLED)\n",
    "        e_lemonade.set('0')\n",
    "\n",
    "\n",
    "def milkshake():\n",
    "    if var13.get() == 1:\n",
    "        textmilkshake.config(state=NORMAL)\n",
    "        textmilkshake.focus()\n",
    "        textmilkshake.delete(0, END)\n",
    "    elif var13.get() == 0:\n",
    "        textmilkshake.config(state=DISABLED)\n",
    "        e_milkshake.set('0')\n",
    "\n",
    "\n",
    "def chocolatemilk():\n",
    "    if var14.get() == 1:\n",
    "        textchocolatemilk.config(state=NORMAL)\n",
    "        textchocolatemilk.focus()\n",
    "        textchocolatemilk.delete(0, END)\n",
    "    elif var14.get() == 0:\n",
    "        textchocolatemilk.config(state=DISABLED)\n",
    "        e_chocolatemilk.set('0')\n",
    "\n",
    "\n",
    "def roohafza():\n",
    "    if var15.get() == 1:\n",
    "        textroohafza.config(state=NORMAL)\n",
    "        textroohafza.focus()\n",
    "        textroohafza.delete(0, END)\n",
    "    elif var15.get() == 0:\n",
    "        textroohafza.config(state=DISABLED)\n",
    "        e_roohafza.set('0')\n",
    "\n",
    "\n",
    "def masalatea():\n",
    "    if var16.get() == 1:\n",
    "        textmasalatea.config(state=NORMAL)\n",
    "        textmasalatea.focus()\n",
    "        textmasalatea.delete(0, END)\n",
    "    elif var16.get() == 0:\n",
    "        textmasalatea.config(state=DISABLED)\n",
    "        e_masalatea.set('0')\n",
    "\n",
    "\n",
    "def badammilk():\n",
    "    if var17.get() == 1:\n",
    "        textbadammilk.config(state=NORMAL)\n",
    "        textbadammilk.focus()\n",
    "        textbadammilk.delete(0, END)\n",
    "    elif var17.get() == 0:\n",
    "        textbadammilk.config(state=DISABLED)\n",
    "        e_badammilk.set('0')\n",
    "\n",
    "\n",
    "def colddrinks():\n",
    "    if var18.get() == 1:\n",
    "        textcolddrinks.config(state=NORMAL)\n",
    "        textcolddrinks.focus()\n",
    "        textcolddrinks.delete(0, END)\n",
    "    elif var18.get() == 0:\n",
    "        textcolddrinks.config(state=DISABLED)\n",
    "        e_coldrinks.set('0')\n",
    "\n",
    "\n",
    "def oreo():\n",
    "    if var19.get() == 1:\n",
    "        textoreo.config(state=NORMAL)\n",
    "        textoreo.focus()\n",
    "        textoreo.delete(0, END)\n",
    "    elif var19.get() == 0:\n",
    "        textoreo.config(state=DISABLED)\n",
    "        e_oreo.set('0')\n",
    "\n",
    "\n",
    "def apple():\n",
    "    if var20.get() == 1:\n",
    "        textapple.config(state=NORMAL)\n",
    "        textapple.focus()\n",
    "        textapple.delete(0, END)\n",
    "    elif var20.get() == 0:\n",
    "        textapple.config(state=DISABLED)\n",
    "        e_apple.set('0')\n",
    "\n",
    "\n",
    "def kitkat():\n",
    "    if var21.get() == 1:\n",
    "        textkitkat.config(state=NORMAL)\n",
    "        textkitkat.focus()\n",
    "        textkitkat.delete(0, END)\n",
    "    elif var21.get() == 0:\n",
    "        textkitkat.config(state=DISABLED)\n",
    "        e_kitkat.set('0')\n",
    "\n",
    "\n",
    "def vanilla():\n",
    "    if var22.get() == 1:\n",
    "        textvanilla.config(state=NORMAL)\n",
    "        textvanilla.focus()\n",
    "        textvanilla.delete(0, END)\n",
    "    elif var22.get() == 0:\n",
    "        textvanilla.config(state=DISABLED)\n",
    "        e_vanilla.set('0')\n",
    "\n",
    "\n",
    "def banana():\n",
    "    if var23.get() == 1:\n",
    "        textbanana.config(state=NORMAL)\n",
    "        textbanana.focus()\n",
    "        textbanana.delete(0, END)\n",
    "    elif var23.get() == 0:\n",
    "        textbanana.config(state=DISABLED)\n",
    "        e_banana.set('0')\n",
    "\n",
    "\n",
    "def brownie():\n",
    "    if var24.get() == 1:\n",
    "        textbrownie.config(state=NORMAL)\n",
    "        textbrownie.focus()\n",
    "        textbrownie.delete(0, END)\n",
    "    elif var24.get() == 0:\n",
    "        textbrownie.config(state=DISABLED)\n",
    "        e_brownie.set('0')\n",
    "\n",
    "\n",
    "def pineapple():\n",
    "    if var25.get() == 1:\n",
    "        textpineapple.config(state=NORMAL)\n",
    "        textpineapple.focus()\n",
    "        textpineapple.delete(0, END)\n",
    "    elif var25.get() == 0:\n",
    "        textpineapple.config(state=DISABLED)\n",
    "        e_pineapple.set('0')\n",
    "\n",
    "\n",
    "def chocolate():\n",
    "    if var26.get() == 1:\n",
    "        textchocolate.config(state=NORMAL)\n",
    "        textchocolate.focus()\n",
    "        textchocolate.delete(0, END)\n",
    "    elif var26.get() == 0:\n",
    "        textchocolate.config(state=DISABLED)\n",
    "        e_chocolate.set('0')\n",
    "\n",
    "\n",
    "def blackforest():\n",
    "    if var27.get() == 1:\n",
    "        textblackforest.config(state=NORMAL)\n",
    "        textblackforest.focus()\n",
    "        textblackforest.delete(0, END)\n",
    "    elif var27.get() == 0:\n",
    "        textblackforest.config(state=DISABLED)\n",
    "        e_blackforest.set('0')\n",
    "\n",
    "\n",
    "\n",
    "root=Tk()\n",
    "\n",
    "root.geometry('1500x800+0+0')\n",
    "\n",
    "root.resizable(0,0)\n",
    "\n",
    "root.title('Coding Academy Restaurant Management System')\n",
    "\n",
    "root.config(bg='black')\n",
    "\n",
    "topFrame=Frame(root,bd=10,relief=RIDGE,bg='firebrick4')\n",
    "topFrame.pack(side=TOP)\n",
    "\n",
    "labelTitle=Label(topFrame,text='Coding Academy Cafe Management System',font=('arial',30,'bold'),fg='black',bd=9,\n",
    "                 bg='white',width=51)\n",
    "labelTitle.grid(row=0,column=0)\n",
    "\n",
    "#frames\n",
    "\n",
    "menuFrame=Frame(root,bd=10,relief=RIDGE,bg='firebrick4')\n",
    "menuFrame.pack(side=LEFT)\n",
    "\n",
    "costFrame=Frame(menuFrame,bd=4,relief=RIDGE,bg='firebrick4',pady=10)\n",
    "costFrame.pack(side=BOTTOM)\n",
    "\n",
    "foodFrame=LabelFrame(menuFrame,text='Food',font=('arial',19,'bold'),bd=10,relief=RIDGE,fg='red4',)\n",
    "foodFrame.pack(side=LEFT)\n",
    "\n",
    "drinksFrame=LabelFrame(menuFrame,text='Drinks',font=('arial',19,'bold'),bd=10,relief=RIDGE,fg='red4')\n",
    "drinksFrame.pack(side=LEFT)\n",
    "\n",
    "cakesFrame=LabelFrame(menuFrame,text='Cakes',font=('arial',19,'bold'),bd=10,relief=RIDGE,fg='red4')\n",
    "cakesFrame.pack(side=LEFT)\n",
    "\n",
    "rightFrame=Frame(root,bd=15,relief=RIDGE,bg='red4')\n",
    "rightFrame.pack(side=RIGHT)\n",
    "\n",
    "calculatorFrame=Frame(rightFrame,bd=1,relief=RIDGE,bg='red4')\n",
    "calculatorFrame.pack()\n",
    "\n",
    "recieptFrame=Frame(rightFrame,bd=4,relief=RIDGE,bg='red4')\n",
    "recieptFrame.pack()\n",
    "\n",
    "buttonFrame=Frame(rightFrame,bd=3,relief=RIDGE,bg='red4')\n",
    "buttonFrame.pack()\n",
    "\n",
    "#Variables\n",
    "\n",
    "var1=IntVar()\n",
    "var2=IntVar()\n",
    "var3=IntVar()\n",
    "var4=IntVar()\n",
    "var5 = IntVar()\n",
    "var6 = IntVar()\n",
    "var7 = IntVar()\n",
    "var8 = IntVar()\n",
    "var9 = IntVar()\n",
    "var10 = IntVar()\n",
    "var11 = IntVar()\n",
    "var12 = IntVar()\n",
    "var13 = IntVar()\n",
    "var14 = IntVar()\n",
    "var15 = IntVar()\n",
    "var16 = IntVar()\n",
    "var17 = IntVar()\n",
    "var18 = IntVar()\n",
    "var19 = IntVar()\n",
    "var20 = IntVar()\n",
    "var21 = IntVar()\n",
    "var22 = IntVar()\n",
    "var23 = IntVar()\n",
    "var24 = IntVar()\n",
    "var25 = IntVar()\n",
    "var26 = IntVar()\n",
    "var27 = IntVar()\n",
    "\n",
    "e_chapathi=StringVar()\n",
    "e_butternaan=StringVar()\n",
    "e_mushroom = StringVar()\n",
    "e_rice = StringVar()\n",
    "e_fish = StringVar()\n",
    "e_mutton = StringVar()\n",
    "e_manchurian = StringVar()\n",
    "e_chicken = StringVar()\n",
    "e_paneer = StringVar()\n",
    "\n",
    "e_lassi=StringVar()\n",
    "e_coffee = StringVar()\n",
    "e_lemonade = StringVar()\n",
    "e_milkshake = StringVar()\n",
    "e_roohafza = StringVar()\n",
    "e_chocolatemilk= StringVar()\n",
    "e_masalatea = StringVar()\n",
    "e_badammilk = StringVar()\n",
    "e_coldrinks = StringVar()\n",
    "\n",
    "e_oreo=StringVar()\n",
    "e_kitkat = StringVar()\n",
    "e_vanilla = StringVar()\n",
    "e_apple = StringVar()\n",
    "e_blackforest = StringVar()\n",
    "e_banana = StringVar()\n",
    "e_brownie = StringVar()\n",
    "e_pineapple = StringVar()\n",
    "e_chocolate = StringVar()\n",
    "\n",
    "costoffoodvar=StringVar()\n",
    "costofdrinksvar=StringVar()\n",
    "costofcakesvar=StringVar()\n",
    "subtotalvar=StringVar()\n",
    "servicetaxvar=StringVar()\n",
    "totalcostvar=StringVar()\n",
    "\n",
    "e_chapathi.set('0')\n",
    "e_butternaan.set('0')\n",
    "e_mushroom.set('0')\n",
    "e_fish.set('0')\n",
    "e_manchurian.set('0')\n",
    "e_rice.set('0')\n",
    "e_mutton.set('0')\n",
    "e_chicken.set('0')\n",
    "e_paneer.set('0')\n",
    "\n",
    "e_lassi.set('0')\n",
    "e_coffee.set('0')\n",
    "e_lemonade.set('0')\n",
    "e_roohafza.set('0')\n",
    "e_milkshake.set('0')\n",
    "e_chocolatemilk.set('0')\n",
    "e_masalatea.set('0')\n",
    "e_badammilk.set('0')\n",
    "e_coldrinks.set('0')\n",
    "\n",
    "e_kitkat.set('0')\n",
    "e_banana.set('0')\n",
    "e_pineapple.set('0')\n",
    "e_apple.set('0')\n",
    "e_chocolate.set('0')\n",
    "e_oreo.set('0')\n",
    "e_blackforest.set('0')\n",
    "e_brownie.set('0')\n",
    "e_vanilla.set('0')\n",
    "\n",
    "##FOOD\n",
    "\n",
    "chapathi=Checkbutton(foodFrame,text='Chapati',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var1\n",
    "                 ,command=chapathi)\n",
    "chapathi.grid(row=0,column=0,sticky=W)\n",
    "\n",
    "butternaan=Checkbutton(foodFrame,text='Butter Naan',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var2\n",
    "                 ,command=butternaan)\n",
    "butternaan.grid(row=1,column=0,sticky=W)\n",
    "\n",
    "fish=Checkbutton(foodFrame,text='Fish',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var3\n",
    "                 ,command=fish)\n",
    "fish.grid(row=2,column=0,sticky=W)\n",
    "\n",
    "mushroom=Checkbutton(foodFrame,text='Mushroom',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var4\n",
    "                  ,command=mushroom)\n",
    "mushroom.grid(row=3,column=0,sticky=W)\n",
    "\n",
    "manchurian=Checkbutton(foodFrame,text='Manchurian',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var5\n",
    "                  ,command=manchurian)\n",
    "manchurian.grid(row=4,column=0,sticky=W)\n",
    "\n",
    "rice=Checkbutton(foodFrame,text='Rice',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var6\n",
    "                   ,command=rice)\n",
    "rice.grid(row=5,column=0,sticky=W)\n",
    "\n",
    "mutton=Checkbutton(foodFrame,text='Mutton',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var7,\n",
    "                   command=mutton)\n",
    "mutton.grid(row=6,column=0,sticky=W)\n",
    "\n",
    "paneer=Checkbutton(foodFrame,text='Paneer',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var8\n",
    "                   ,command=paneer)\n",
    "paneer.grid(row=7,column=0,sticky=W)\n",
    "\n",
    "chicken=Checkbutton(foodFrame,text='Chicken',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var9\n",
    "                    ,command=chicken)\n",
    "chicken.grid(row=8,column=0,sticky=W)\n",
    "\n",
    "#Entry Fields for Food Items\n",
    "\n",
    "textchapathi=Entry(foodFrame,font=('arial',18,'bold'),bd=7,width=6,state=DISABLED,textvariable=e_chapathi)\n",
    "textchapathi.grid(row=0,column=1)\n",
    "\n",
    "textbutternaan=Entry(foodFrame,font=('arial',18,'bold'),bd=7,width=6,state=DISABLED,textvariable=e_butternaan)\n",
    "textbutternaan.grid(row=1,column=1)\n",
    "\n",
    "textfish=Entry(foodFrame,font=('arial',18,'bold'),bd=7,width=6,state=DISABLED,textvariable=e_fish)\n",
    "textfish.grid(row=2,column=1)\n",
    "\n",
    "textmushroom = Entry(foodFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_mushroom)\n",
    "textmushroom.grid(row=3, column=1)\n",
    "\n",
    "textmanchurian = Entry(foodFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_manchurian)\n",
    "textmanchurian.grid(row=4, column=1)\n",
    "\n",
    "textrice = Entry(foodFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_rice)\n",
    "textrice.grid(row=5, column=1)\n",
    "\n",
    "textmutton = Entry(foodFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_mutton)\n",
    "textmutton.grid(row=6, column=1)\n",
    "\n",
    "textpaneer = Entry(foodFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_paneer)\n",
    "textpaneer.grid(row=7, column=1)\n",
    "\n",
    "textchicken = Entry(foodFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_chicken)\n",
    "textchicken.grid(row=8, column=1)\n",
    "\n",
    "#Drinks\n",
    "\n",
    "lassi=Checkbutton(drinksFrame,text='Lassi',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var10\n",
    "                  ,command=lassi)\n",
    "lassi.grid(row=0,column=0,sticky=W)\n",
    "\n",
    "coffee=Checkbutton(drinksFrame,text='Coffee',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var11\n",
    "                   ,command=coffee)\n",
    "coffee.grid(row=1,column=0,sticky=W)\n",
    "\n",
    "lemonade=Checkbutton(drinksFrame,text='Lemonade',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var12\n",
    "                   ,command=lemonade)\n",
    "lemonade.grid(row=2,column=0,sticky=W)\n",
    "\n",
    "milkshake=Checkbutton(drinksFrame,text='Milkshake',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var13\n",
    "                     ,command=milkshake)\n",
    "milkshake.grid(row=3,column=0,sticky=W)\n",
    "\n",
    "chocolatemilk=Checkbutton(drinksFrame,text='Chocolate milk',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var14\n",
    "                     ,command=chocolatemilk)\n",
    "chocolatemilk.grid(row=4,column=0,sticky=W)\n",
    "\n",
    "roohafza=Checkbutton(drinksFrame,text='Green tea',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var15\n",
    "                     ,command=roohafza)\n",
    "roohafza.grid(row=5,column=0,sticky=W)\n",
    "\n",
    "masalatea=Checkbutton(drinksFrame,text='Masala Tea',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var16\n",
    "                      ,command=masalatea)\n",
    "masalatea.grid(row=6,column=0,sticky=W)\n",
    "\n",
    "badammilk=Checkbutton(drinksFrame,text='Badam Milk',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var17\n",
    "                      ,command=badammilk)\n",
    "badammilk.grid(row=7,column=0,sticky=W)\n",
    "\n",
    "colddrinks=Checkbutton(drinksFrame,text='Cold Drinks',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var18\n",
    "                       ,command=colddrinks)\n",
    "colddrinks.grid(row=8,column=0,sticky=W)\n",
    "\n",
    "#entry fields for drink items\n",
    "\n",
    "textlassi = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_lassi)\n",
    "textlassi.grid(row=0, column=1)\n",
    "\n",
    "textcoffee = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_coffee)\n",
    "textcoffee.grid(row=1, column=1)\n",
    "\n",
    "textlemonade = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_lemonade)\n",
    "textlemonade.grid(row=2, column=1)\n",
    "\n",
    "textmilkshake = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_milkshake)\n",
    "textmilkshake.grid(row=3, column=1)\n",
    "\n",
    "textchocolatemilk = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_chocolatemilk)\n",
    "textchocolatemilk.grid(row=4, column=1)\n",
    "\n",
    "textroohafza = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_roohafza)\n",
    "textroohafza.grid(row=5, column=1)\n",
    "\n",
    "textmasalatea = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED,textvariable=e_masalatea)\n",
    "textmasalatea.grid(row=6, column=1)\n",
    "\n",
    "textbadammilk = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_badammilk)\n",
    "textbadammilk.grid(row=7, column=1)\n",
    "\n",
    "textcolddrinks = Entry(drinksFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_coldrinks)\n",
    "textcolddrinks.grid(row=8, column=1)\n",
    "\n",
    "#Cakes\n",
    "\n",
    "oreocake=Checkbutton(cakesFrame,text='Butterscotch ',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var19\n",
    "                     ,command=oreo)\n",
    "oreocake.grid(row=0,column=0,sticky=W)\n",
    "\n",
    "applecake=Checkbutton(cakesFrame,text='Normal Cake',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var20\n",
    "                      ,command=apple)\n",
    "applecake.grid(row=1,column=0,sticky=W)\n",
    "\n",
    "kitkatcake=Checkbutton(cakesFrame,text='Kitkat',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var21\n",
    "                       ,command=kitkat)\n",
    "kitkatcake.grid(row=2,column=0,sticky=W)\n",
    "\n",
    "vanillacake=Checkbutton(cakesFrame,text='Vanilla',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var22\n",
    "                        ,command=vanilla)\n",
    "vanillacake.grid(row=3,column=0,sticky=W)\n",
    "\n",
    "bananacake=Checkbutton(cakesFrame,text='Banana',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var23\n",
    "                       ,command=banana)\n",
    "bananacake.grid(row=4,column=0,sticky=W)\n",
    "\n",
    "browniecake=Checkbutton(cakesFrame,text='Brownie',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var24\n",
    "                        ,command=brownie)\n",
    "browniecake.grid(row=5,column=0,sticky=W)\n",
    "\n",
    "pineapplecake=Checkbutton(cakesFrame,text='Pineapple',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var25\n",
    "                          ,command=pineapple)\n",
    "pineapplecake.grid(row=6,column=0,sticky=W)\n",
    "\n",
    "chocolatecake=Checkbutton(cakesFrame,text='Chocolate',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var26\n",
    "                          ,command=chocolate)\n",
    "chocolatecake.grid(row=7,column=0,sticky=W)\n",
    "\n",
    "blackforestcake=Checkbutton(cakesFrame,text='Black Forest',font=('arial',18,'bold'),onvalue=1,offvalue=0,variable=var27\n",
    "                            ,command=blackforest)\n",
    "blackforestcake.grid(row=8,column=0,sticky=W)\n",
    "\n",
    "#entry fields for cakes\n",
    "\n",
    "textoreo = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_oreo)\n",
    "textoreo.grid(row=0, column=1)\n",
    "\n",
    "textapple = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_apple)\n",
    "textapple.grid(row=1, column=1)\n",
    "\n",
    "textkitkat = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_kitkat)\n",
    "textkitkat.grid(row=2, column=1)\n",
    "\n",
    "textvanilla = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_vanilla)\n",
    "textvanilla.grid(row=3, column=1)\n",
    "\n",
    "textbanana = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_banana)\n",
    "textbanana.grid(row=4, column=1)\n",
    "\n",
    "textbrownie = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_brownie)\n",
    "textbrownie.grid(row=5, column=1)\n",
    "\n",
    "textpineapple = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_pineapple)\n",
    "textpineapple.grid(row=6, column=1)\n",
    "\n",
    "textchocolate = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED, textvariable=e_chocolate)\n",
    "textchocolate.grid(row=7, column=1)\n",
    "\n",
    "textblackforest = Entry(cakesFrame, font=('arial', 18, 'bold'), bd=7, width=6, state=DISABLED,textvariable=e_blackforest)\n",
    "textblackforest.grid(row=8, column=1)\n",
    "\n",
    "#costlabels & entry fields\n",
    "\n",
    "labelCostofFood=Label(costFrame,text='Cost of Food',font=('arial',16,'bold'),bg='firebrick4',fg='white')\n",
    "labelCostofFood.grid(row=0,column=0)\n",
    "\n",
    "textCostofFood=Entry(costFrame,font=('arial',16,'bold'),bd=6,width=14,state='readonly',textvariable=costoffoodvar)\n",
    "textCostofFood.grid(row=0,column=1,padx=41)\n",
    "\n",
    "labelCostofDrinks=Label(costFrame,text='Cost of Drinks',font=('arial',16,'bold'),bg='firebrick4',fg='white')\n",
    "labelCostofDrinks.grid(row=1,column=0)\n",
    "\n",
    "textCostofDrinks=Entry(costFrame,font=('arial',16,'bold'),bd=6,width=14,state='readonly',textvariable=costofdrinksvar)\n",
    "textCostofDrinks.grid(row=1,column=1,padx=41)\n",
    "\n",
    "labelCostofCakes=Label(costFrame,text='Cost of Cakes',font=('arial',16,'bold'),bg='firebrick4',fg='white')\n",
    "labelCostofCakes.grid(row=2,column=0)\n",
    "\n",
    "textCostofCakes=Entry(costFrame,font=('arial',16,'bold'),bd=6,width=14,state='readonly',textvariable=costofcakesvar)\n",
    "textCostofCakes.grid(row=2,column=1,padx=41)\n",
    "\n",
    "labelSubTotal=Label(costFrame,text='Sub Total',font=('arial',16,'bold'),bg='firebrick4',fg='white')\n",
    "labelSubTotal.grid(row=0,column=2)\n",
    "\n",
    "textSubTotal=Entry(costFrame,font=('arial',16,'bold'),bd=6,width=14,state='readonly',textvariable=subtotalvar)\n",
    "textSubTotal.grid(row=0,column=3,padx=41)\n",
    "\n",
    "labelServiceTax=Label(costFrame,text='Service Tax',font=('arial',16,'bold'),bg='firebrick4',fg='white')\n",
    "labelServiceTax.grid(row=1,column=2)\n",
    "\n",
    "textServiceTax=Entry(costFrame,font=('arial',16,'bold'),bd=6,width=14,state='readonly',textvariable=servicetaxvar)\n",
    "textServiceTax.grid(row=1,column=3,padx=41)\n",
    "\n",
    "labelTotalCost=Label(costFrame,text='Total Cost',font=('arial',16,'bold'),bg='firebrick4',fg='white')\n",
    "labelTotalCost.grid(row=2,column=2)\n",
    "\n",
    "textTotalCost=Entry(costFrame,font=('arial',16,'bold'),bd=6,width=14,state='readonly',textvariable=totalcostvar)\n",
    "textTotalCost.grid(row=2,column=3,padx=41)\n",
    "\n",
    "#Buttons\n",
    "\n",
    "buttonTotal=Button(buttonFrame,text='Total',font=('arial',14,'bold'),fg='white',bg='red4',bd=3,padx=5,\n",
    "                   command=totalcost)\n",
    "buttonTotal.grid(row=0,column=0)\n",
    "\n",
    "buttonReceipt=Button(buttonFrame,text='Receipt',font=('arial',14,'bold'),fg='white',bg='red4',bd=3,padx=5\n",
    "                     ,command=receipt)\n",
    "buttonReceipt.grid(row=0,column=1)\n",
    "\n",
    "buttonReset=Button(buttonFrame,text='Reset',font=('arial',14,'bold'),fg='white',bg='red4',bd=3,padx=5,\n",
    "                   command=reset)\n",
    "buttonReset.grid(row=0,column=4)\n",
    "\n",
    "#textarea for receipt\n",
    "\n",
    "textReceipt=Text(recieptFrame,font=('arial',12,'bold'),bd=3,width=45,height=27)\n",
    "textReceipt.grid(row=0,column=0)\n",
    "\n",
    "\n",
    "\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d0733a3",
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install tk()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61c7604f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "768eca18",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
